### ISSUE TITLE
Sint Maarten vs Saint Martin (en.yml)

### ISSUE THREAD

**Issue by tomekw** [onomojo/i18n-country-translations#29]
According to Wikipedia (https://en.wikipedia.org/wiki/Saint_Martin) it's `Saint Martin` and it's defined as Sint Maarten here https://github.com/onomojo/i18n-country-translations/blob/master/rails/locale/iso_639-1/en.yml#L222

@onomojo do you believe it's possible to adjust it? I will be happy to prepare a pull request for this.

**Comment by whit537** [comment]
I believe this can be closed with https://github.com/onomojo/i18n-country-translations/pull/30.

**Comment by tomekw** [comment]
👍

**Comment by Mangoov** [comment]
I don't think this should of changed, Sint Maarten and Saint Martin are completely different. Saint Martin refers to the island as a whole, but it is split into 2 different constituencies with Saint Martin & Sint Maarten. 

Having it be Saint Martin as well is very confusing since there will be two Saint Martin with their own ISO code. I think this should probably be reverted
